### ISSUE TITLE
Windows binaries

### ISSUE THREAD

**Issue by robertha64** [stronnag/bbl2kml#1]
Poor Windows users binaries ?

**Comment by stronnag** [comment]
What exactly is the problem with the Window's binary?

**Comment by robertha64** [comment]
I can not find it. There is no working link bbl2kml.exe for me at code page.

**Comment by stronnag** [comment]
try "Releases", that's where binaries live.

**Comment by robertha64** [comment]
Sorry find it, I did not look on whole page.
