### ISSUE TITLE
Decode ArduPilot OpenTX logs

### ISSUE THREAD

**Issue by stronnag** [stronnag/bbl2kml#13]
For the benefit of pilots who can't remember which firmware they're flying, it would be convenient if the `flightlog2kml` could also decode OpenTX logs from ArduPilot.

**Comment by stronnag** [comment]
Of course, some example logs would be useful.

**Comment by stronnag** [comment]
Experimental Linux/x86_64 binary
[flightlog2kml_ardupilot.tar.gz](https://github.com/stronnag/bbl2kml/files/6151903/flightlog2kml_ardupilot.tar.gz)

**Comment by skorokithakis** [comment]
That works great, thanks!

**Comment by stronnag** [comment]
Feature released in 0.9.7
