### ISSUE TITLE
Decode raw smartport CRSF telemetry

### ISSUE THREAD

**Issue by marianomd** [stronnag/bbl2kml#20]
Hi! I'm using opentx on a flysky i6x, which doesn't have SD card support, so there are no CSV files available. But we have telemetry mirror being output on the smartport, which in turn goes to the CrazyDude's Android app through bluetooth (HC-05).

Finally that app generates a .log binary file with the raw CRSF telemetry from ExpressLRS.

I couldn't find support for this decoding, how far do you think bbl2kml is from doing this?

Here's a feature request for basically the same: https://github.com/CrazyDude1994/android-taranis-smartport-telemetry/issues/76

I may be able to help with this, but would have to check if it's easier here or in the Android app.

Thanks in advance!

**Comment by marianomd** [comment]
Hi, thanks for the prompt response!

Here is the file. It doesn't have headers.

[crsf.zip](https://github.com/stronnag/bbl2kml/files/11200439/crsf.zip)

**Comment by stronnag** [comment]
![image](https://user-images.githubusercontent.com/158229/231167201-94b89b03-401f-4ece-92cb-755cb35dc3ee.png)

**Comment by stronnag** [comment]
using the now [documented](https://stronnag.github.io/mwptools/replay-tools/#mwp-raw-logs) `mwp-log-replay` into mwp.

**Comment by stronnag** [comment]
Note that the time is arbitrary as there is no temporal meta-data. 
* There are multiple flights in the log (this is the 2nd)
* There's some junk positions in the first flight).

And I'm really not minded to add CRSF/Sport etc etc to the bbl2kml suite, but maybe mwp could be persuaded to write out an OTX format CSV as it already knows how to do the protocol decoding (and bbl2kml suite knows about OTX CSV).

**Comment by stronnag** [comment]
FYI, from mwp's standalone `crsfparser` (development branch, corruption in your file revealed the need for some more validation).
[crsf-decoded.tar.gz](https://github.com/stronnag/bbl2kml/files/11200735/crsf-decoded.tar.gz)

**Comment by marianomd** [comment]
Thanks for your time Jonathan! The lack of timing information renders these logs almost useless. Now I get why the android app doesn't have a play button. Anyway, I'll explore the replay and crsfparser tools.

**Comment by marianomd** [comment]
CRSF to OTX CSV functionality is exactly what we need, but, if done on the android app, we could inject the missing timing information (receive time). Do you have some pointer to the CSV format?

I've been looking at the android code, and it already parses the CRSF and handles each type of telemetry event, so it would be relatively simple to implement I think, adding a class that listens to these events and outputs the CSV.

**Comment by stronnag** [comment]
> CRSF to OTX CSV functionality is exactly what we need, but, if done on the android app, we could inject the missing timing information (receive time). Do you have some pointer to the CSV format?

It really depends what you want to use it for. If you use the OpenTX / EdgeTX format then you have access to many extant OTX/ETX analysis tools (including `flightlog2kml` and other `bbl2kml` tools). The downside is that you're using OTX "sensor" packing for all fields. For example, GPS parameters are encoded into "Tmp2".

The  `flightlog2kml`  code in [otxreader.go](https://github.com/stronnag/bbl2kml/blob/f586157767351fe579c5c9fe0583a882545b9cba/pkg/otx/otxreader.go#L252) shows the fields  `flightlog2kml`  requires.  Note some data extraction is duplicated; Smartport and CRSF encode some data differently (e.g. RSSI. Flight Mode, VBat).

I've attached an example OTX CSV; please note:
* This  was from Smartport, not  CRSF
* The locations have been adjusted to protect the guilty (it is not my log).

[otx-test-log.csv.gz](https://github.com/stronnag/bbl2kml/files/11204965/otx-test-log.csv.gz)

The following items are the OTX headers from a ELRSv3 EdgeTX CSV log, the actual items are version dependent; a V2 log has fewer items.

Note also that the units are required.

```
Date         Time           1RSS(dB)   2RSS(dB)   RQly(%)   RSNR(dB)   ANT   RFMD   TPWR(mW)   TRSS(dB)   TQly(%)   TSNR(dB)   Ptch(rad)   Roll(rad)   Yaw(rad)   FM     VSpd(m/s)   GPS   GSpd(m/s)   Hdg(°)   Alt(m)   Sats   RxBt(V)   Curr(A)   Capa(mAh)   Bat%(%)   Rud   Ele   Thr     Ail   S1     6P      S2    EX1     EX2     EX3     EX4     LS    RS    SA   SB   SC   SD   SE   SF   SG   SH   SI   SJ   LSW                  CH1(us)   CH2(us)   CH3(us)   CH4(us)   CH5(us)   CH6(us)   CH7(us)   CH8(us)   CH9(us)   CH10(us)   CH11(us)   CH12(us)   CH13(us)   CH14(us)   CH15(us)   CH16(us)   CH17(us)   CH18(us)   CH19(us)   CH20(us)   CH21(us)   CH22(us)   CH23(us)   CH24(us)   CH25(us)   CH26(us)   CH27(us)   CH28(us)   CH29(us)   CH30(us)   CH31(us)   CH32(us)   TxBat(V)
```

Feel free to ask further questions. I'm all in favour of more inter-operable INAV analysis tools.

**Comment by marianomd** [comment]
Thank you for the thorough explanation! It will be of great help. When I get it done I'll let you know here.

**Comment by marianomd** [comment]
Hi! I have an initial version of the feature almost ready.

Do you have a recommendation of how often I should output a row to the csv? 100 ms should be good enough? Or too much?

Outputting a line each time I get a value would result in a redundant and large file.

**Comment by marianomd** [comment]
Already pushed it, I used 200ms for the moment.

https://github.com/RomanLut/android-taranis-smartport-telemetry/pull/40
