### ISSUE TITLE
cannot process datalog (.TXT) w10 - Inav 6.1.1

### ISSUE THREAD

**Issue by fedemj2** [stronnag/bbl2kml#21]
Hello! I am trying to process the .txt running with flightlog2kml.exe and the pop-up window to process is not activated.
I have tried only with the blackbox decoder and I got the 4 files to see in googlemaps, but I can't process the TXT to get the KMZ.
I clarify that the .json file was edited with the // indicating the corresponding path.
I have even deactivated the antivirus in case that would be generating a problem, but on the other hand the other files could be generated by the decode.
windows 10 64 bit operating system
Inav 6.1.1
Thank you very much if you can help me
![Screenshot_27](https://github.com/stronnag/bbl2kml/assets/141748153/ddde52ae-d3ad-410d-9508-a8b25d79662c)
![Screenshot_28](https://github.com/stronnag/bbl2kml/assets/141748153/bb6f06fd-ce5d-4161-857a-6b33d64c445f)

**Comment by stronnag** [comment]
I cannot help you with the logs ....

**Comment by fedemj2** [comment]
would you like the logs to test?

**Comment by stronnag** [comment]
Your log works fine here (win10 virtual machine, powershell)

```
PS C:\Users\win10> .\flightlog2kml.exe LOG00012.TXT
Log      : LOG00012.TXT / 1
Flight   :  on 2023-08-06 12:54:47
Firmware : INAV 6.1.1 (42ced253) SPEEDYBEEF405WING of Jun 13 2023 12:28:36
Size     : 1.90 MB
Duration : 07:03
Altitude : 114.3 m at 03:39
Speed    : 31.4 m/s at 03:07
Range    : 1153 m at 05:09
Current  : 29.1 A at 01:26
Distance : 6732 m
Disarm   : Landing
Output   : C:\Users\win10\Documents\KML Logs\LOG00012.1.kmz
```

Also works with `fl2xui`:

![Screenshot 2023-08-08 154939](https://github.com/stronnag/bbl2kml/assets/158229/d8e51454-0851-4c0b-81a0-d6c0299c943d)

And the KMZ is viewable:

![Screenshot from 2023-08-08 15-58-09](https://github.com/stronnag/bbl2kml/assets/158229/2d14d38f-7223-4a43-8430-70f078e00f53)

So there is no problem with either `flightlog2kml` or the log file. I am not qualified to help with Windows issues.

**Comment by fedemj2** [comment]
incredible! how do i use that? do you have any video explaining it?

**Comment by stronnag** [comment]
No video, it has comprehensive documentation.
