### ISSUE TITLE
cannont process datalog

### ISSUE THREAD

**Issue by robertha64** [stronnag/bbl2kml#3]
![image](https://user-images.githubusercontent.com/39700425/103416147-9ce63c00-4b85-11eb-95cb-c4e9e600d3f8.png)

get run time error index out of range on whatever inav log file tried

(using european win setting - comma is delimiter for decimals, can cause issues ?)  

Any hints ?

**Comment by stronnag** [comment]
Please provide the BB log file
However, I suspect it's because there is no geospatial data in that particular log (index). I'm just fixing that now.

**Comment by robertha64** [comment]
[LOG00092.TXT](https://github.com/stronnag/bbl2kml/files/5757668/LOG00092.TXT)
Hi Jonathan, log attached. Thank you for all your work for Inav and enjoy New Year.
Robert

**Comment by robertha64** [comment]
Hi - working now, my version of blackbox decode was too old. Once I did use 0.45RC2 is OK.

**Comment by stronnag** [comment]
It is also the case the `range` (distance from home), is not calculated correctly with `blackbox_decoder` prior to 0.4.5-rcX, so thank you for the issue.

**Comment by robertha64** [comment]
Its a great tool.
![image](https://user-images.githubusercontent.com/39700425/103418295-547f4c00-4b8e-11eb-844e-a08032e2904b.png)
